// @ts-check
// Flat config generated by the @nuxt/eslint module (.nuxt/eslint.config.mjs).
// It bundles the Nuxt/Vue/TS rules plus the nuxt-link-checker broken-link
// rules (valid-route / valid-sitemap-link), which are injected automatically
// via the `eslint:config:addons` hook. Run `nuxi prepare` if the import is
// missing or the route list (.nuxt/link-checker/routes.json) is stale.
import withNuxt from './.nuxt/eslint.config.mjs'

export default withNuxt(
  {
    ignores: [
      '.data/**',
      'public/**',
      'static/**',
    ],
  },
)
